# Generated by Django 2.0 on 2018-11-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcharacteristics',
            name='allowed_quota',
            field=models.IntegerField(default=0),
        ),
    ]
