# Generated by Django 2.1.3 on 2018-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='filter',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
