# Generated by Django 2.1.3 on 2018-12-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
