# Generated by Django 2.1.3 on 2018-12-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_creation_date']},
        ),
    ]
