# Generated by Django 2.1.3 on 2018-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20181229_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
