# Generated by Django 2.1.3 on 2018-12-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20181229_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='swift',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
