# Generated by Django 2.1.3 on 2018-12-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20181223_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['review_creation_date']},
        ),
    ]
