# Generated by Django 2.1.3 on 2018-12-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20181225_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_creation_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-review_creation_date']},
        ),
    ]
