# Generated by Django 2.1.3 on 2018-12-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20181230_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcharacteristics',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
