# Generated by Django 2.1.3 on 2018-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20181225_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
