# Generated by Django 2.1.3 on 2018-12-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20181225_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
