# Generated by Django 2.1.3 on 2018-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20181225_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcharacteristics',
            name='integral_choices',
            field=models.ManyToManyField(related_name='room_characteristics', to='engine.IntegralChoice'),
        ),
        migrations.AlterField(
            model_name='roomcharacteristics',
            name='radio_choices',
            field=models.ManyToManyField(related_name='room_characteristics', to='engine.RadioChoice'),
        ),
    ]
