# Generated by Django 2.1.3 on 2018-12-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20181225_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='features',
            field=models.ManyToManyField(related_name='dormitories', to='engine.FeatureFilter'),
        ),
    ]
