# Generated by Django 2.1.3 on 2018-12-27 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20181225_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptphoto',
            name='upload_receipt_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_update_date',
            field=models.DateField(auto_now=True, default=datetime.date(2018, 12, 27)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
